# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N6PMmpFFBuTq2QtPPEXe9hXb4YdtCJV0

Determine si el proceso es espontaneo o debe ser forzado

Desarrolla un programa en Python que, dadas las condiciones de temperatura y voltaje, determine si un proceso de electrólisis es espontáneo o si requiere ser forzado. Define funciones que simulen la electrólisis espontánea y forzada, y utiliza condiciones aleatorias para evaluar si la electrólisis ocurre de manera natural o necesita intervención externa. ¿Cómo podrías estructurar el código para reflejar las condiciones específicas que hacen que la electrólisis sea espontánea o forzada?"
"""

import random

class ElectrolisisSimulador:
    def __init__(self, temperatura, voltaje):
        self.temperatura = temperatura
        self.voltaje = voltaje

    def es_espontaneo(self):
        return self.temperatura > 50 and self.voltaje > 2.0

    def es_forzado(self):
        return self.temperatura < 20 or self.voltaje < 1.0

def simular_electrolisis(temperatura, voltaje):
    simulador = ElectrolisisSimulador(temperatura, voltaje)
    espontaneo = simulador.es_espontaneo()
    forzado = simulador.es_forzado()
    return espontaneo, forzado

def imprimir_resultados(simulador):
    print(f"\nCondiciones de Electrólisis - Temperatura: {simulador.temperatura}°C, Voltaje: {simulador.voltaje} V")

    if simulador.es_espontaneo():
        print("La electrólisis es espontánea bajo estas condiciones.")
    else:
        print("Se necesita intervención externa para forzar la electrólisis.")

    if simulador.es_forzado():
        print("Se necesita intervención externa para forzar la electrólisis.")
    else:
        print("La electrólisis puede ocurrir espontáneamente bajo estas condiciones.")

# Simulación de condiciones aleatorias
temperatura_espontanea = random.randint(25, 100)
voltaje_espontaneo = random.uniform(1.5, 3.0)

temperatura_forzada = random.randint(1, 30)
voltaje_forzado = random.uniform(0.5, 1.5)

# Simulación y resultados
simulador_1 = ElectrolisisSimulador(temperatura_espontanea, voltaje_espontaneo)
espontaneo_1, forzado_1 = simulador_1.es_espontaneo(), simulador_1.es_forzado()

simulador_2 = ElectrolisisSimulador(temperatura_forzada, voltaje_forzado)
espontaneo_2, forzado_2 = simulador_2.es_espontaneo(), simulador_2.es_forzado()

# Imprimir resultados
imprimir_resultados(simulador_1)
imprimir_resultados(simulador_2)